# Dockerfile.python37-slim
FROM python:3.7-slim
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir django
RUN apt-get update && apt-get install sqlite3 -y
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]