# Dockerfile.alpine
FROM python:3.10-alpine
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir django
RUN apk add sqlite
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]